name: Build & Push to ECR

on:
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: ap-southeast-2
  ECR_REGISTRY: 333813598365.dkr.ecr.ap-southeast-2.amazonaws.com
  ECR_REPOSITORY: hackthon/team2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug package.json in PR
        run: |
          echo "EVENT: $GITHUB_EVENT_NAME"
          echo "SHA: $GITHUB_SHA"
          echo "REF: $GITHUB_REF"
          pwd
          ls -la
          echo "---- search package.json ----"
          find . -maxdepth 4 -name package.json -print -exec ls -la {} \; -exec wc -c {} \; -exec cat -n {} \;


      - name: Install Dependencies
        working-directory: deployment_microservice
        run: npm install


      - name: Start service and health check
        working-directory: deployment_microservice
        run: |
          node appointment-service.js &
          sleep 3
          curl -f http://localhost:3001/health

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.access_key }}
          aws-secret-access-key: ${{ secrets.secret_key }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: deployment_microservice
        run: |
          IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          docker build -t "$IMAGE_URI" .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

 