


name: Build & Push to ECR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: ap-southeast-2
  ECR_REGISTRY: 333813598365.dkr.ecr.ap-southeast-2.amazonaws.com
  ECR_REPOSITORY: hackthon/team2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

   
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Run Node Script
        run: node appointment-service.js


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.access_key }}
          aws-secret-access-key: ${{ secrets.secret_key }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build Docker image
        run: |
          IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          docker build -t "$IMAGE_URI" .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Push Docker image to ECR (only on main push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push "$IMAGE_URI"


      - name: Tag & Push latest (only on main push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          LATEST_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest"
          docker tag "$IMAGE_URI" "$LATEST_URI"
          docker push "$LATEST_URI"
